my.app.message = From Config Server, testing refresh scope.
#Eureka location
eureka.client.service-url.defaultZone = http://localhost:8761/eureka
#Generating random instance id
eureka.instance.instance-id=${spring.application.name}:${random.value}
